[env:nrf]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840
framework = arduino
monitor_speed = 115200
build_flags = -I../shared/include
lib_deps =
	adafruit/Adafruit SSD1306
	adafruit/Adafruit GFX Library
	adafruit/Adafruit SHT31 Library
	adafruit/Adafruit SGP30 Sensor

