[env:esp32]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
build_flags = -I../shared/include -DARDUINO_USB_CDC_ON_BOOT=1
board_build.arduino.usb_mode = 1
board_build.arduino.usb_cdc_on_boot = 1
monitor_speed = 115200
upload_speed = 115200
